# Simple IoT Platform - Docker Compose
version: '3.8'

services:
  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2
    container_name: iot-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
    restart: unless-stopped

  # FastAPI Application
  api:
    build: .
    container_name: iot-api
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    volumes:
      - ./data:/app/data
    depends_on:
      - mqtt
    restart: unless-stopped

volumes:
  mqtt_data:
