# Template Cloudflare Tunnel config
# Replace tunnel name and credentials file for your setup
tunnel: iot-platform
credentials-file: /etc/cloudflared/iot-platform.json

ingress:
  # Public demo dashboard
  - hostname: demo.your-domain.com
    service: http://localhost:8080
  
  # Access-protected control panel
  - hostname: control.your-domain.com
    service: http://localhost:8080
  
  # Access-protected MQTT WebSocket endpoint
  - hostname: mqtt.your-domain.com
    service: http://localhost:8080
  
  # Admin interface (optional)
  - hostname: admin.your-domain.com
    service: http://localhost:8080
  
  # Catch-all
  - service: http_status:404

# Optional: metrics endpoint for monitoring
metrics: 0.0.0.0:2000
